%% -*- mode: erlang -*-
%% -*- tab-width: 4;erlang-indent-level: 4;indent-tabs-mode: nil -*-
%% ex: ts=4 sw=4 sts ft=erlang et

case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        CONFIG;
    false -> % rebar 2.x or older
        %% Rebuild deps, possibly including those that have been moved to
        %% profiles
        [{deps, [
            {b64fast, {git, "https://github.com/zuckschwerdt/b64fast", {branch, master}}},
            {erlias,  {git, "https://github.com/choptastic/erlias", {branch, master}}},
            {poolboy, {git, "https://github.com/devinus/poolboy", {branch, master}}},
            {epgsql,  {git, "https://github.com/epgsql/epgsql", {branch, master}}},
            {decimal, {git, "https://github.com/egobrain/decimal", {branch, master}}},
            %% This version is modified for rebar2
            {epgsql_decimal,  {git, "https://github.com/choptastic/epgsql_decimal", {branch, master}}},
            {mysql,   {git, "https://github.com/mysql-otp/mysql-otp", {branch, master}}}
        ]} | lists:keydelete(deps, 1, CONFIG)]
end.
