name: SQL Bridge Tests & Dialyzer
on: push

jobs:
  linux:
    name: OTP ${{ matrix.otp_version }} (${{ matrix.mysql }}/PG ${{ matrix.pg}})
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            mysql: "mariadb-11.8"
            pg: "17"
            otp_version: '27.x'
            rebar3_version: "3.24.0"
          - os: ubuntu-24.04
            mysql: "mysql-9.2"
            pg: "17"
            otp_version: '27.x'
            rebar3_version: "3.23.0"
          - os: ubuntu-24.04
            mysql: "mysql-8.4"
            pg: "17"
            otp_version: '26.x'
            rebar3_version: "3.23.0"
          - os: ubuntu-24.04
            mysql: "mysql-8.4"
            pg: "16"
            otp_version: '26.x'
            rebar3_version: "3.23.0"  
          - os: ubuntu-22.04
            mysql: "mariadb-11.1"
            pg: "16"
            otp_version: '26.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-22.04
            mysql: "mariadb-10.11"
            pg: "15"
            otp_version: '26.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-22.04
            mysql: "mariadb-10.11"
            pg: "15"
            otp_version: '25.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-22.04
            mysql: "mariadb-10.2"
            pg: "14"
            otp_version: '25.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-22.04
            mysql: "mysql-8.1"
            pg: "13"
            otp_version: '25.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-22.04
            mysql: "mysql-8.0"
            pg: "12"
            otp_version: '24.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-22.04
            mysql: "mysql-5.7"
            pg: "11"
            otp_version: '24.x'
            rebar3_version: "3.22.1"
          - os: ubuntu-20.04
            mysql: "mysql-5.6"
            pg: "14.9"
            otp_version: '23.x'
            rebar3_version: "3.19.0"

    steps:
      - name: Install OTP ${{matrix.otp_version}}
        uses: erlef/setup-beam@v1
        with:
          version-type: loose
          otp-version: ${{ matrix.otp_version}}
          rebar3-version: ${{ matrix.rebar3_version}}

      # https://github.com/marketplace/actions/actions-setup-mysql
      - name: Install ${{ matrix.mysql }}
        uses: shogo82148/actions-setup-mysql@v1.42.0
          #env:
          #  ImageOS: ubuntu20
        with:
          mysql-version: ${{ matrix.mysql }}
          ## I have no idea why, but if I didn't have the actions-setup-mysql
          ## rule set up first, the new user config just wouldn't take.
          user: sql_bridge_user
          password: sql_bridge_test_password

      # https://github.com/marketplace/actions/setup-postgresql-with-postgresql-extensions-and-unprivileged-user
      - name: Install Postgres ${{ matrix.pg }}
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: ${{ matrix.pg }}

      - name: Checkout SQL bridge
        uses: actions/checkout@v3

      - name: Load databases & Run SQL Bridge eunit tests
        run: make test
        env:
          MYSQLHOST: localhost
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Run Dialyzer
        run: make dialyzer
